import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type LanguageCode =
  | 'as'  // Assamese
  | 'bn'  // Bengali
  | 'brx' // Bodo
  | 'doi' // Dogri
  | 'gu'  // Gujarati
  | 'hi'  // Hindi
  | 'kn'  // Kannada
  | 'ks'  // Kashmiri
  | 'kok' // Konkani
  | 'mai' // Maithili
  | 'ml'  // Malayalam
  | 'mni' // Manipuri
  | 'mr'  // Marathi
  | 'ne'  // Nepali
  | 'or'  // Odia
  | 'pa'  // Punjabi
  | 'en'  // English
  | 'sat' // Santhali
  | 'sd'  // Sindhi
  | 'ta'  // Tamil
  | 'te'  // Telugu
  | 'ur'; // Urdu

export interface LanguageInfo {
  code: LanguageCode;
  name: string;
  nativeName: string;
  region: string;
  script: string;
}

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', region: 'Assam / NER', script: 'Bengali-Assamese' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', region: 'Tripura, Assam, WB', script: 'Bengali' },
  { code: 'brx', name: 'Bodo', nativeName: 'बड़ो', region: 'Bodoland / Assam', script: 'Devanagari' },
  { code: 'doi', name: 'Dogri', nativeName: 'डोगरी', region: 'Jammu & Kashmir / HP', script: 'Devanagari' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', region: 'Gujarat', script: 'Gujarati' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', region: 'Pan-India', script: 'Devanagari' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', region: 'Karnataka', script: 'Kannada' },
  { code: 'ks', name: 'Kashmiri', nativeName: 'کٲشُر / कॉशुर', region: 'Jammu & Kashmir', script: 'Perso-Arabic / Devanagari' },
  { code: 'kok', name: 'Konkani', nativeName: 'कोंकणी', region: 'Goa, Maharashtra', script: 'Devanagari' },
  { code: 'mai', name: 'Maithili', nativeName: 'मैथिली', region: 'Bihar, Jharkhand', script: 'Devanagari' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', region: 'Kerala', script: 'Malayalam' },
  { code: 'mni', name: 'Manipuri', nativeName: 'মৈতৈলোন্ / মণিপুরী', region: 'Manipur / NER', script: 'Bengali / Meitei Mayek' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', region: 'Maharashtra', script: 'Devanagari' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', region: 'Sikkim, Darjeeling / NER', script: 'Devanagari' },
  { code: 'or', name: 'Odia (formerly Oriya)', nativeName: 'ଓଡ଼ିଆ', region: 'Odisha', script: 'Odia' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', region: 'Punjab', script: 'Gurmukhi' },
  { code: 'en', name: 'English', nativeName: 'English', region: 'India & International', script: 'Latin' },
  { code: 'sat', name: 'Santhali (Santali)', nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ / संथाली', region: 'Jharkhand, Assam tea-estates', script: 'Ol Chiki / Devanagari' },
  { code: 'sd', name: 'Sindhi', nativeName: 'سنڌي / सिंधी', region: 'Western India', script: 'Perso-Arabic / Devanagari' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', region: 'Tamil Nadu', script: 'Tamil' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', region: 'Andhra Pradesh, Telangana', script: 'Telugu' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', region: 'Pan-India, J&K', script: 'Perso-Arabic' }
];

export type TranslationKey =
  | 'appName'
  | 'tagline'
  | 'navDashboard'
  | 'navMap'
  | 'navReports'
  | 'reportHazard'
  | 'live'
  | 'offline'
  | 'syncPending'
  | 'emergencyActive'
  | 'emergencyMode'
  | 'searchPlaceholder'
  | 'heroSubtitle'
  | 'calculateSafeCorridor'
  | 'roadAccessibility'
  | 'ofArteries'
  | 'activeHazards'
  | 'blockedRoads'
  | 'fleetInTransit'
  | 'registeredCarriers'
  | 'delayedMissions'
  | 'needsReroute'
  | 'arterialHighwayStatus'
  | 'openGisMap'
  | 'aiBriefingTitle'
  | 'optimizeRoutes'
  | 'weatherRadar'
  | 'driverMission'
  | 'pickedUp'
  | 'inTransit'
  | 'delayed'
  | 'delivered'
  | 'viewGpsRoute'
  | 'reportBlockageSos'
  | 'verificationQueue'
  | 'verifyBlock'
  | 'reject'
  | 'languageSettings'
  | 'broadcastLanguages'
  | 'broadcastDesc'
  | 'selectDisplayLang'
  | 'activeBroadcastCount'
  | 'applySelection'
  | 'selectAll'
  | 'clearAll'
  | 'highways'
  | 'hazards'
  | 'vehicles'
  | 'riskZones'
  | 'emergencyRoutes'
  | 'corridorSafeBypass'
  | 'allWeather'
  | 'caution'
  | 'blocked';

export const TRANSLATIONS: Record<LanguageCode, Record<TranslationKey, string>> = {
  en: {
    appName: 'RouteMind NER',
    tagline: 'Regional Logistics & Terrain Intelligence',
    navDashboard: '1. Dashboard',
    navMap: '2. Live GIS Operations',
    navReports: '3. Logistical Reports & Logs',
    reportHazard: 'Report Hazard',
    live: 'Live',
    offline: 'Offline',
    syncPending: 'Sync',
    emergencyActive: 'SOS Active',
    emergencyMode: 'Emergency Mode',
    searchPlaceholder: 'Search highways (NH-27, NH-10), districts, vehicles, incidents...',
    heroSubtitle: 'Continuous corridor telemetry across 8 North Eastern states — monitoring Sela Pass snowpacks, Teesta waterflows, high-elevation road fractures, and priority medical supply routes.',
    calculateSafeCorridor: 'Calculate Safe Corridor',
    roadAccessibility: 'Road Accessibility',
    ofArteries: 'Of Arteries',
    activeHazards: 'Active Hazards',
    blockedRoads: 'Blocked',
    fleetInTransit: 'Convoys in Transit',
    registeredCarriers: 'Registered Carriers',
    delayedMissions: 'Delayed Missions',
    needsReroute: 'Needs Re-Route',
    arterialHighwayStatus: 'Arterial Highway Status',
    openGisMap: 'Open Interactive GIS',
    aiBriefingTitle: 'AI Logistics Dispatch',
    optimizeRoutes: 'Optimize Routes',
    weatherRadar: 'Hill Radar & Precipitation',
    driverMission: 'Driver Active Mission HUD',
    pickedUp: '1. Picked Up',
    inTransit: '2. In Transit',
    delayed: '3. Delayed',
    delivered: '4. Delivered',
    viewGpsRoute: 'View GPS Route & Safe Bypass',
    reportBlockageSos: 'Report Road Blockage (SOS)',
    verificationQueue: 'Field Hazard Verification Queue',
    verifyBlock: 'Verify & Block Corridor',
    reject: 'Reject',
    languageSettings: 'Language & Broadcast Settings',
    broadcastLanguages: 'Multilingual Operational Broadcast',
    broadcastDesc: 'Select multiple regional languages for automated disaster alerts, road warnings, and convoy dispatch bulletins.',
    selectDisplayLang: 'Active UI Display Language',
    activeBroadcastCount: 'Languages Configured for Field Broadcast',
    applySelection: 'Save & Apply Languages',
    selectAll: 'Select All (22)',
    clearAll: 'Reset to English',
    highways: 'Highways',
    hazards: 'Hazards',
    vehicles: 'Vehicles',
    riskZones: 'Risk Zones',
    emergencyRoutes: 'Emergency Routes',
    corridorSafeBypass: 'Safe Bypass Alternate',
    allWeather: 'ACCESSIBLE',
    caution: 'CAUTION',
    blocked: 'BLOCKED'
  },
  as: {
    appName: 'RouteMind NER',
    tagline: 'আঞ্চলিক পৰিবহন আৰু ভূ-প্ৰকৃতি চোৰাংচোৱাগিৰি',
    navDashboard: '১. ডেচব\'ৰ্ড',
    navMap: '২. লাইভ জি.আই.এছ. কাৰ্যকলাপ',
    navReports: '৩. পৰিবহন প্ৰতিবেদন আৰু লগ',
    reportHazard: 'বিপদ প্ৰতিবেদন দিয়ক',
    live: 'সক্ৰিয়',
    offline: 'অফলাইন',
    syncPending: 'সংমিশ্ৰণ (Sync)',
    emergencyActive: 'জৰুৰীকালীন সক্ৰিয়',
    emergencyMode: 'জৰুৰীকালীন ব্যৱস্থা',
    searchPlaceholder: 'ৰাষ্ট্ৰীয় ঘাইপথ (NH-27, NH-10), জিলা, বাহন সন্ধান কৰক...',
    heroSubtitle: 'উত্তৰ-পূৰ্বাঞ্চলৰ ৮খন ৰাজ্যৰ বাবে নিৰন্তৰ পথ নিৰীক্ষণ — ছেলা পাছ, তিস্তা নদীৰ বানপানী আৰু জৰুৰী ঔষধ পৰিবহন সুৰক্ষা।',
    calculateSafeCorridor: 'সুৰক্ষিত পথ গণনা কৰক',
    roadAccessibility: 'পথ সুগমতা',
    ofArteries: 'মুখ্য পথৰ',
    activeHazards: 'সক্ৰিয় বিপদসমূহ',
    blockedRoads: 'অৱৰুদ্ধ',
    fleetInTransit: 'যাত্ৰাত থকা কনভয়',
    registeredCarriers: 'পঞ্জীকৃত বাহনসমূহ',
    delayedMissions: 'বিলম্বিত পৰিবহন',
    needsReroute: 'বিকল্প পথ প্ৰয়োজন',
    arterialHighwayStatus: 'প্ৰধান ঘাইপথ অৱস্থা',
    openGisMap: 'জি.আই.এছ. মানচিত্ৰ খোলক',
    aiBriefingTitle: 'কৃত্ৰিম বুদ্ধিমত্তা পথ নিৰ্দেশনা',
    optimizeRoutes: 'বিকল্প পথ নিৰ্ণয়',
    weatherRadar: 'বতৰ আৰু বৃষ্টিপাত ৰাডাৰ',
    driverMission: 'চালকৰ সক্ৰিয় মিছন এইচ.ইউ.ডি.',
    pickedUp: '১. সংগ্ৰহ কৰা হ\'ল',
    inTransit: '২. যাত্ৰাত আছে',
    delayed: '৩. বিলম্বিত',
    delivered: '৪. যোগান সম্পূৰ্ণ',
    viewGpsRoute: 'জি.পি.এছ. বিকল্প পথ চাওক',
    reportBlockageSos: 'পথ অৱৰোধ প্ৰতিবেদন দিয়ক (SOS)',
    verificationQueue: 'বিপদ পৰীক্ষণ অগ্ৰাধিকাৰ',
    verifyBlock: 'পৰীক্ষা কৰি পথ বন্ধ কৰক',
    reject: 'প্ৰত্যাখ্যান',
    languageSettings: 'ভাষা আৰু সম্প্ৰচাৰ ছেটিংছ',
    broadcastLanguages: 'বহুভাষিক সতৰ্কবাৰ্তা সম্প্ৰচাৰ',
    broadcastDesc: 'জৰুৰীকালীন সতৰ্কবাৰ্তা আৰু চালকৰ জাননী সম্প্ৰচাৰৰ বাবে বহুতো আঞ্চলিক ভাষা বাছক।',
    selectDisplayLang: 'প্ৰদৰ্শন ভাষা বাছক',
    activeBroadcastCount: 'ফিল্ড সম্প্ৰচাৰৰ বাবে নিৰ্বাচিত ভাষা',
    applySelection: 'সংৰক্ষণ কৰক',
    selectAll: 'সকলো বাছক (২২)',
    clearAll: 'ইংৰাজীলৈ ঘূৰক',
    highways: 'ঘাইপথসমূহ',
    hazards: 'বিপদসমূহ',
    vehicles: 'বাহনসমূহ',
    riskZones: 'ঝুঁকিপূৰ্ণ অঞ্চল',
    emergencyRoutes: 'জৰুৰীকালীন পথ',
    corridorSafeBypass: 'সুৰক্ষিত বাইপাছ',
    allWeather: 'সুগম',
    caution: 'সতৰ্ক',
    blocked: 'অৱৰুদ্ধ'
  },
  bn: {
    appName: 'RouteMind NER',
    tagline: 'আঞ্চলিক লজিস্টিক ও ভূখণ্ড গোয়েন্দা তথ্য',
    navDashboard: '১. ড্যাশবোর্ড',
    navMap: '২. লাইভ জিআইএস অপারেশন',
    navReports: '৩. অপারেশনাল রিপোর্ট ও লগ',
    reportHazard: 'বিপদ রিপোর্ট করুন',
    live: 'অনলাইন',
    offline: 'অফলাইন',
    syncPending: 'সিঙ্ক করুন',
    emergencyActive: 'জরুরী এসওএস সক্রিয়',
    emergencyMode: 'জরুরী মোড',
    searchPlaceholder: 'মহাসড়ক (NH-27, NH-10), জেলা, যানবাহন অনুসন্ধান করুন...',
    heroSubtitle: 'উত্তর-পূর্বের ৮টি রাজ্যে নিরবচ্ছিন্ন মহাসড়ক নজরদারি — সেলা পাস, তিস্তা নদীর বন্যা ও জরুরি চিকিৎসা রসদ সহায়তা।',
    calculateSafeCorridor: 'নিরাপদ পথ গণনা করুন',
    roadAccessibility: 'সড়ক সুগমতা',
    ofArteries: 'প্রধান সড়ক',
    activeHazards: 'সক্রিয় বিপদসমূহ',
    blockedRoads: 'অবরুদ্ধ সড়ক',
    fleetInTransit: 'চলাচলরত কনভয়',
    registeredCarriers: 'নিবন্ধিত পরিবহন',
    delayedMissions: 'বিলম্বিত চালান',
    needsReroute: 'বিকল্প পথ প্রয়োজন',
    arterialHighwayStatus: 'প্রধান মহাসড়কের অবস্থা',
    openGisMap: 'জিআইএস মানচিত্র দেখুন',
    aiBriefingTitle: 'এআই লজিস্টিক ব্রিফিং',
    optimizeRoutes: 'বিকল্প রুট অপ্টিমাইজ করুন',
    weatherRadar: 'পাহাড়ি আবহাওয়া ও বৃষ্টিপাত',
    driverMission: 'ড্রাইভারের সক্রিয় মিশন কন্ট্রোল',
    pickedUp: '১. লোড সম্পন্ন',
    inTransit: '২. ট্রানজিটে আছে',
    delayed: '৩. বিলম্বিত',
    delivered: '৪. ডেলিভারি সম্পন্ন',
    viewGpsRoute: 'বিকল্প রুট দেখুন',
    reportBlockageSos: 'সড়ক অবরোধের এসওএস দিন',
    verificationQueue: 'বিপদ যাচাইকরণ কিউ',
    verifyBlock: 'যাচাই ও সড়ক অবরুদ্ধ করুন',
    reject: 'বাতিল',
    languageSettings: 'ভাষা ও সম্প্রচার সেটিংস',
    broadcastLanguages: 'বহুভাষিক সতর্কতা সম্প্রচার',
    broadcastDesc: 'জরুরী সতর্কতা এবং চালকদের নির্দেশিকা পাঠানোর জন্য আঞ্চলিক ভাষাসমূহ নির্বাচন করুন।',
    selectDisplayLang: 'প্রদর্শন ভাষা নির্বাচন করুন',
    activeBroadcastCount: 'সক্রিয় সম্প্রচার ভাষা',
    applySelection: 'প্রয়োগ করুন',
    selectAll: 'সব নির্বাচন (২২)',
    clearAll: 'ডিফল্ট ইংরেজি',
    highways: 'হাইওয়েসমূহ',
    hazards: 'বিপদসমূহ',
    vehicles: 'যানবাহন',
    riskZones: 'ঝুঁকিপূর্ণ অঞ্চল',
    emergencyRoutes: 'জরুরি রুট',
    corridorSafeBypass: 'নিরাপদ বাইপাস',
    allWeather: 'গম্য',
    caution: 'সতর্কতা',
    blocked: 'অবরুদ্ধ'
  },
  brx: {
    appName: 'RouteMind NER',
    tagline: 'लजिस्टिक्स आरो हा-जोमा सिस्तिम',
    navDashboard: '१. देसबर्ड',
    navMap: '२. जि.आइ.एस. मखौ',
    navReports: '३. रादाब आरो रिपर्ट',
    reportHazard: 'खैफोद जाथाय खौरां हर',
    live: 'लाइभ',
    offline: 'अफलाइन',
    syncPending: 'सिंक खालाम',
    emergencyActive: 'गाखोनाय एस.ओ.एस',
    emergencyMode: 'गोख्रों थासारि',
    searchPlaceholder: 'लामा (NH-27), जिल्ला, गारि नायगिर...',
    heroSubtitle: 'सा-सानजा भारतनि लामा आरो गोजौ हालामनि खौरां मोननाय।',
    calculateSafeCorridor: 'रैखागोनां लामा दिहुन',
    roadAccessibility: 'लामा थांनाय-फैनाय',
    ofArteries: 'गाहाय लामा',
    activeHazards: 'दावबायनाय खैफोद',
    blockedRoads: 'बन्द लामा',
    fleetInTransit: 'थांगासिनो थानाय गारिफोर',
    registeredCarriers: 'गारिफोरनि अनजिमा',
    delayedMissions: 'लेथ जाबाय',
    needsReroute: 'गुबुन लामा नांगौ',
    arterialHighwayStatus: 'गाहाय लामानि महर',
    openGisMap: 'मानचित्र नाय',
    aiBriefingTitle: 'AI लामा खौरां',
    optimizeRoutes: 'लामा मोजां खालाम',
    weatherRadar: 'अखा आरो बार',
    driverMission: 'सालायग्रा मिसन',
    pickedUp: '१. लांबाय',
    inTransit: '२. लामायाव दं',
    delayed: '३. लेथ',
    delivered: '४. सहैबाय',
    viewGpsRoute: 'GPS लामा नाय',
    reportBlockageSos: 'लामा बन्द SOS',
    verificationQueue: 'नायबिजिरनाय',
    verifyBlock: 'फोरमान खालाम आरो बन्द खालाम',
    reject: 'नेवसि',
    languageSettings: 'राव आरो फोसावनाय सेटिंस',
    broadcastLanguages: 'गोबां रावनि खौरां फोसावनाय',
    broadcastDesc: 'सालायग्रा आरो खैफोद खौरां फोसावनो गोबां राव सायख\',',
    selectDisplayLang: 'दिनथिग्रा राव सायख\'',
    activeBroadcastCount: 'सायख\'नाय रावफोर',
    applySelection: 'लागु खालाम',
    selectAll: 'गासै सायख\' (२२)',
    clearAll: 'English आव थां',
    highways: 'गाहाय लामाफोर',
    hazards: 'खैफोदफोर',
    vehicles: 'गारिफोर',
    riskZones: 'खैफोद ओनसोल',
    emergencyRoutes: 'गोख्रों लामा',
    corridorSafeBypass: 'रैखागोनां बायपास',
    allWeather: 'थांनो हागौ',
    caution: 'सांग्रां',
    blocked: 'बन्द'
  },
  hi: {
    appName: 'RouteMind NER',
    tagline: 'पूर्वोत्तर रसद एवं पर्वतीय भूभाग आसूचना मंच',
    navDashboard: '1. डैशबोर्ड',
    navMap: '2. लाइव जीआईएस मानचित्र',
    navReports: '3. लॉजिस्टिक्स रिपोर्ट एवं लॉग',
    reportHazard: 'खतरे की रिपोर्ट करें',
    live: 'लाइव',
    offline: 'ऑफलाइन',
    syncPending: 'सिंक करें',
    emergencyActive: 'आपातकालीन मोड सक्रिय',
    emergencyMode: 'आपातकालीन प्रोटोकॉल',
    searchPlaceholder: 'राजमार्ग (NH-27, NH-10), जिले, वाहन, भूस्खलन खोजें...',
    heroSubtitle: 'पूर्वोत्तर के 8 राज्यों में निरंतर पहाड़ी गलियारा निगरानी — सेला दर्रा हिमस्खलन, तीस्ता बाढ़ व जीवनरक्षक दवाओं की सुरक्षित आवाजाही।',
    calculateSafeCorridor: 'सुरक्षित वैकल्पिक मार्ग खोजें',
    roadAccessibility: 'सड़क सुगम्यता',
    ofArteries: 'मुख्य धमनियों का',
    activeHazards: 'सक्रिय खतरे / भूस्खलन',
    blockedRoads: 'अवरुद्ध',
    fleetInTransit: 'पारगमन में वाहन दल',
    registeredCarriers: 'पंजीकृत वाहन',
    delayedMissions: 'विलंबित खेप',
    needsReroute: 'पुनर्मार्ग आवश्यक',
    arterialHighwayStatus: 'प्रमुख राष्ट्रीय राजमार्ग स्थिति',
    openGisMap: 'इंटरएक्टिव जीआईएस खोलें',
    aiBriefingTitle: 'एआई लॉजिस्टिक्स ब्रीफिंग',
    optimizeRoutes: 'मार्ग अनुकूलन',
    weatherRadar: 'पर्वतीय मौसम व वर्षा रडार',
    driverMission: 'चालक सक्रिय मिशन एचयूडी',
    pickedUp: '1. प्राप्त हुआ',
    inTransit: '2. रास्ते में है',
    delayed: '3. विलंबित',
    delivered: '4. वितरित',
    viewGpsRoute: 'जीपीएस सुरक्षित बाईपास देखें',
    reportBlockageSos: 'सड़क अवरोध रिपोर्ट (SOS)',
    verificationQueue: 'क्षेत्रीय खतरा सत्यापन कतार',
    verifyBlock: 'सत्यापित कर मार्ग बंद करें',
    reject: 'अस्वीकार करें',
    languageSettings: 'भाषा एवं प्रसारण सेटिंग्स',
    broadcastLanguages: 'बहुभाषी आपातकालीन प्रसारण',
    broadcastDesc: 'फील्ड सलाह, सड़क चेतावनियों और चालक संदेशों के लिए एक से अधिक भाषाओं का चयन करें।',
    selectDisplayLang: 'सक्रिय इंटरफ़ेस भाषा',
    activeBroadcastCount: 'प्रसारण के लिए चयनित भाषाएं',
    applySelection: 'सहेजें और लागू करें',
    selectAll: 'सभी चुनें (22 भाषाएं)',
    clearAll: 'अंग्रेज़ी पर रीसेट करें',
    highways: 'राजमार्ग',
    hazards: 'खतरे',
    vehicles: 'वाहन',
    riskZones: 'जोखिम क्षेत्र',
    emergencyRoutes: 'आपातकालीन मार्ग',
    corridorSafeBypass: 'सुरक्षित बाईपास',
    allWeather: 'सुगम्य',
    caution: 'सावधानी',
    blocked: 'अवरुद्ध'
  },
  mni: {
    appName: 'RouteMind NER',
    tagline: 'নোংপোক-অৱাং থংনা লম্বী অমসুং লজিস্টিক ইন্তেলিজেন্স',
    navDashboard: '১. দেশবোর্দ',
    navMap: '২. লাইভ জি.আই.এস লম্বী',
    navReports: '৩. ওপরেস্নেল রিপোর্ত',
    reportHazard: 'খুদোংথীবা রিপোর্ত তৌবীয়ু',
    live: 'লাইভ',
    offline: 'ওফলাইন',
    syncPending: 'সিঙ্ক তৌবীয়ু',
    emergencyActive: 'এস.ও.এস এক্তিব',
    emergencyMode: 'ইমর্জেন্সী মোদ',
    searchPlaceholder: 'হাইভেম্বী (NH-27), দিস্ত্রিক্ত, গারী থিবীয়ু...',
    heroSubtitle: 'নোংপোক-অৱাংগী স্তেত ৮গী লম্বী-থোং য়েংশিনবা অমসুং মরুওইবা পোৎলম পুথোক-পুশিনগী তেংবাং।',
    calculateSafeCorridor: 'শেফ ওইবা লম্বী খঙদোকউ',
    roadAccessibility: 'লম্বী চৎপা য়াবা',
    ofArteries: 'মরুওইবা লম্বীশিংগী',
    activeHazards: 'হৌজিক ওইরিবা খুদোংথীবা',
    blockedRoads: 'লম্বী থিংজিনবা',
    fleetInTransit: 'চৎথোক-চৎশিন তৌরিবা গারীশিং',
    registeredCarriers: 'রেজিস্তর তৌরবা গারী',
    delayedMissions: 'থেন্থরবা মিসনশিং',
    needsReroute: 'অতোপ্পা লম্বী চংবা',
    arterialHighwayStatus: 'হাইভেম্বীশিংগী ফিবম',
    openGisMap: 'জিআইএস মেপ হাংদোকউ',
    aiBriefingTitle: 'AI লজিস্টিক ব্রিফিং',
    optimizeRoutes: 'শেফ লম্বী শেম্বা',
    weatherRadar: 'নোং-চিঙগী ফিবম',
    driverMission: 'দ্রাইভরগী মিসন কন্ট্রোল',
    pickedUp: '১. লোইনা পুখৎলে',
    inTransit: '২. লম্বীদা চৎলি',
    delayed: '৩. থেন্থরে',
    delivered: '৪. য়ৌরে',
    viewGpsRoute: 'GPS অল্তর্নেত লম্বী য়েংবীয়ু',
    reportBlockageSos: 'লম্বী থিংজিনবা SOS',
    verificationQueue: 'চেক তৌনবগী লাইন',
    verifyBlock: 'চেক তৌদুনা লম্বী থিংবীয়ু',
    reject: 'য়াদবা',
    languageSettings: 'লোন অমসুং ব্রোদকাস্ত সেতিংস',
    broadcastLanguages: 'লোন কয়াদা খুদোংথীবা ফোঙদোকপা',
    broadcastDesc: 'ইমর্জেন্সী এলার্ত অমসুং দ্রাইভরগী নোতিস পীনবা লোন কয়া খনবীয়ু।',
    selectDisplayLang: 'ইন্তর্ফেস লোন খনবীয়ু',
    activeBroadcastCount: 'ব্রোদকাস্ত তৌনবা লোনশিং',
    applySelection: 'এপ্লাই তৌবীয়ু',
    selectAll: 'লোইনা খনবা (২২)',
    clearAll: 'English দা হনবা',
    highways: 'হাইভেম্বীশিং',
    hazards: 'খুদোংথীবাশিং',
    vehicles: 'গারীশিং',
    riskZones: 'খুদোংথীনবা জোন',
    emergencyRoutes: 'ইমর্জেন্সী রুত',
    corridorSafeBypass: 'বাইপাস লম্বী',
    allWeather: 'চৎপা য়াবা',
    caution: 'চেকশিনবা',
    blocked: 'থিংজিনবা'
  },
  ne: {
    appName: 'RouteMind NER',
    tagline: 'उत्तर-पूर्वी क्षेत्रीय रसद तथा पहाडी भूभाग इन्टेलिजेन्स',
    navDashboard: '१. ड्यासबोर्ड',
    navMap: '२. प्रत्यक्ष जीआईएस नक्शा',
    navReports: '३. परिचालन प्रतिवेदन र लग',
    reportHazard: 'पहिरो / खतरा रिपोर्ट गर्नुहोस्',
    live: 'प्रत्यक्ष',
    offline: 'अफलाइन',
    syncPending: 'सिङ्क गर्नुहोस्',
    emergencyActive: 'आपतकालीन सक्रिय',
    emergencyMode: 'संकटकालीन प्रोटोकल',
    searchPlaceholder: 'राजमार्ग (NH-10, NH-27), जिल्ला, गाडी खोज्नुहोस्...',
    heroSubtitle: 'उत्तर-पूर्वका ८ राज्यहरूमा सडक निगरानी — सेला पास, टिस्टा नदीको बाढी र जीवनरक्षक आपूर्ति मार्गहरू।',
    calculateSafeCorridor: 'सुरक्षित वैकल्पिक मार्ग खोज्नुहोस्',
    roadAccessibility: 'सडक पहुँच',
    ofArteries: 'मुख्य मार्गहरूको',
    activeHazards: 'सक्रिय खतराहरू',
    blockedRoads: 'सडक बन्द',
    fleetInTransit: 'चालक दल पारवहनमा',
    registeredCarriers: 'दर्ता भएका सवारी',
    delayedMissions: 'ढिलाइ भएका ढुवानी',
    needsReroute: 'वैकल्पिक मार्ग आवश्यक',
    arterialHighwayStatus: 'प्रमुख राजमार्ग अवस्था',
    openGisMap: 'जीआईएस नक्शा खोल्नुहोस्',
    aiBriefingTitle: 'एआई रसद सल्लाह',
    optimizeRoutes: 'मार्ग अनुकूलन',
    weatherRadar: 'पहाडी मौसम र वर्षा',
    driverMission: 'चालक सक्रिय मिसन ड्यासबोर्ड',
    pickedUp: '१. लोड गरियो',
    inTransit: '२. बाटोमा छ',
    delayed: '३. ढिलो भयो',
    delivered: '४. डेलिभर गरियो',
    viewGpsRoute: 'जीपीएस वैकल्पिक मार्ग हेर्नुहोस्',
    reportBlockageSos: 'सडक अवरोध रिपोर्ट (SOS)',
    verificationQueue: 'खतरा प्रमाणीकरण लाइन',
    verifyBlock: 'प्रमाणित गरी मार्ग बन्द गर्नुहोस्',
    reject: 'अस्वीकार गर्नुहोस्',
    languageSettings: 'भाषा र प्रसारण सेटिङहरू',
    broadcastLanguages: 'बहुभाषिक आपतकालीन चेतावनी प्रसारण',
    broadcastDesc: 'चालक र सुरक्षाकर्मीहरूका लागि चेतावनी प्रसारण गर्न बहु भाषाहरू चयन गर्नुहोस्।',
    selectDisplayLang: 'प्रदर्शित भाषा छान्नुहोस्',
    activeBroadcastCount: 'प्रसारणका लागि छानिएका भाषाहरू',
    applySelection: 'लागू गर्नुहोस्',
    selectAll: 'सबै छान्नुहोस् (२२)',
    clearAll: 'अंग्रेजीमा रिसेट गर्नुहोस्',
    highways: 'राजमार्गहरू',
    hazards: 'खतराहरू',
    vehicles: 'सवारीसाधनहरू',
    riskZones: 'जोखिम क्षेत्रहरू',
    emergencyRoutes: 'आपतकालीन मार्गहरू',
    corridorSafeBypass: 'सुरक्षित बाइपास',
    allWeather: 'खुला',
    caution: 'सतर्क',
    blocked: 'बन्द'
  },
  // Other scheduled languages with consistent fallback mapping to provide high-quality localized headings
  doi: {
    appName: 'RouteMind NER',
    tagline: 'क्षेत्रीय लजिस्टिक्स ते पहाड़ी इलाका आसूचना',
    navDashboard: '1. डैशबोर्ड',
    navMap: '2. लाइव जीआईएस नक्शा',
    navReports: '3. रसद रिपोर्ट ते लाग',
    reportHazard: 'खतरे दी रिपोर्ट करो',
    live: 'लाइव',
    offline: 'ऑफलाइन',
    syncPending: 'सिंक करो',
    emergencyActive: 'संकटकालीन सक्रिय',
    emergencyMode: 'आपातकालीन मोड',
    searchPlaceholder: 'राजमार्ग, जिले, गड्डियां लभो...',
    heroSubtitle: 'पहाड़ी रस्ते दी निगरानी ते सुरक्षित रसद आवाजाही।',
    calculateSafeCorridor: 'सुरक्षित रस्ता कड्डो',
    roadAccessibility: 'सड़क उपलब्धता',
    ofArteries: 'मुख्य रस्ते',
    activeHazards: 'सक्रिय खतरे',
    blockedRoads: 'बंद',
    fleetInTransit: 'रास्ते च गड्डियां',
    registeredCarriers: 'दर्ज गड्डियां',
    delayedMissions: 'लेट मिशन',
    needsReroute: 'नुआं रस्ता चाहिदा',
    arterialHighwayStatus: 'राजमार्ग दी हालत',
    openGisMap: 'नक्शा खोल्लो',
    aiBriefingTitle: 'एआई सलाह',
    optimizeRoutes: 'रस्ता ठीक करो',
    weatherRadar: 'मौसम ते बारिश',
    driverMission: 'ड्राइवर मिशन',
    pickedUp: '1. चक्की लया',
    inTransit: '2. रास्ते च',
    delayed: '3. लेट',
    delivered: '4. पुजाई दित्ता',
    viewGpsRoute: 'जीपीएस रस्ता दिक्खो',
    reportBlockageSos: 'रस्ता बंद SOS',
    verificationQueue: 'सत्यापन कतार',
    verifyBlock: 'सत्यापित करिये बंद करो',
    reject: 'रद्द',
    languageSettings: 'बोली ते प्रसारण सेटिंग्स',
    broadcastLanguages: 'बहुभाषी चेतावनी प्रसारण',
    broadcastDesc: 'चेतावनी प्रसारण आस्तै बोलियां चुनो।',
    selectDisplayLang: 'प्रदर्शनी बोली चुनो',
    activeBroadcastCount: 'चुने दी बोलियां',
    applySelection: 'लागू करो',
    selectAll: 'सब्भै चुनो (22)',
    clearAll: 'अंग्रेज़ी',
    highways: 'राजमार्ग',
    hazards: 'खतरे',
    vehicles: 'गड्डियां',
    riskZones: 'जोखिम क्षेत्र',
    emergencyRoutes: 'आपातकालीन मार्ग',
    corridorSafeBypass: 'सुरक्षित बाईपास',
    allWeather: 'खुल्ला',
    caution: 'होशियार',
    blocked: 'बंद'
  },
  gu: {
    appName: 'RouteMind NER',
    tagline: 'પ્રાદેશિક લોજિસ્ટિક્સ અને પર્વતીય ઇન્ટેલિજન્સ',
    navDashboard: '1. ડેશબોર્ડ',
    navMap: '2. લાઈવ જીઆઈએસ મેપ',
    navReports: '3. રિપોર્ટ્સ અને લોગ્સ',
    reportHazard: 'જોખમની જાણ કરો',
    live: 'લાઈવ',
    offline: 'ઑફલાઇન',
    syncPending: 'સિંક કરો',
    emergencyActive: 'કટોકટી મોડ સક્રિય',
    emergencyMode: 'ઇમરજન્સી પ્રોટોકોલ',
    searchPlaceholder: 'હાઈવે (NH-27), જિલ્લાઓ, વાહનો શોધો...',
    heroSubtitle: 'પૂર્વોત્તર ભારતના ૮ રાજ્યોમાં સતત હાઇવે મોનિટરિંગ અને સલામત લોજિસ્ટિક્સ.',
    calculateSafeCorridor: 'સુરક્ષિત માર્ગ ગણો',
    roadAccessibility: 'માર્ગ સુલભતા',
    ofArteries: 'મુખ્ય માર્ગોના',
    activeHazards: 'સક્રિય જોખમો',
    blockedRoads: 'બંધ રસ્તાઓ',
    fleetInTransit: 'માર્ગમાં વાહનો',
    registeredCarriers: 'નોંધાયેલા વાહનો',
    delayedMissions: 'વિલંબિત મિશન',
    needsReroute: 'વૈકલ્પિક માર્ગ જરૂરી',
    arterialHighwayStatus: 'હાઇવે સ્થિતિ',
    openGisMap: 'જીઆઈએસ નકશો જુઓ',
    aiBriefingTitle: 'AI લોજિસ્ટિક્સ બ્રીફિંગ',
    optimizeRoutes: 'રૂટ ઑપ્ટિમાઇઝેશન',
    weatherRadar: 'પર્વતીય હવામાન અને વરસાદ',
    driverMission: 'ડ્રાઈવર મિશન કંટ્રોલ',
    pickedUp: '1. પિક-અપ પૂર્ણ',
    inTransit: '2. રસ્તામાં છે',
    delayed: '3. વિલંબિત',
    delivered: '4. પહોંચાડાયેલ',
    viewGpsRoute: 'જીપીએસ બાયપાસ જુઓ',
    reportBlockageSos: 'રસ્તો બ્લૉક રિપોર્ટ (SOS)',
    verificationQueue: 'જોખમ ચકાસણી કતાર',
    verifyBlock: 'ચકાસીને રસ્તો બંધ કરો',
    reject: 'નકારો',
    languageSettings: 'ભાષા અને પ્રસારણ સેટિંગ્સ',
    broadcastLanguages: 'બહુભાષીય ચેતવણી પ્રસારણ',
    broadcastDesc: 'ડ્રાઇવરો અને કટોકટી ચેતવણીઓ મોકલવા માટે બહુવિધ ભાષાઓ પસંદ કરો.',
    selectDisplayLang: 'ડિસ્પ્લે ભાષા પસંદ કરો',
    activeBroadcastCount: 'પસંદ કરેલી પ્રસારણ ભાષાઓ',
    applySelection: 'લાગુ કરો',
    selectAll: 'બધી પસંદ કરો (22)',
    clearAll: 'અંગ્રેજીમાં રીસેટ',
    highways: 'હાઇવે',
    hazards: 'જોખમો',
    vehicles: 'વાહનો',
    riskZones: 'જોખમી વિસ્તારો',
    emergencyRoutes: 'કટોકટી રૂટ્સ',
    corridorSafeBypass: 'સુરક્ષિત બાયપાસ',
    allWeather: 'ચાલુ',
    caution: 'સાવધાની',
    blocked: 'બંધ'
  },
  kn: {
    appName: 'RouteMind NER',
    tagline: 'ಪ್ರಾದೇಶಿಕ ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಮತ್ತು ಭೂಪ್ರದೇಶ ಇಂಟೆಲಿಜೆನ್ಸ್',
    navDashboard: '1. ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    navMap: '2. ಲೈವ್ ಜಿಐಎಸ್ ಕಾರ್ಯಾಚರಣೆ',
    navReports: '3. ಲಾಜಿಸ್ಟಿಕಲ್ ವರದಿಗಳು',
    reportHazard: 'ಅಪಾಯ ವರದಿ ಮಾಡಿ',
    live: 'ಲೈವ್',
    offline: 'ಆಫ್‌ಲೈನ್',
    syncPending: 'ಸಿಂಕ್ ಮಾಡಿ',
    emergencyActive: 'ತುರ್ತು ಮೋಡ್ ಸಕ್ರಿಯ',
    emergencyMode: 'ತುರ್ತು ಪ್ರೋಟೋಕಾಲ್',
    searchPlaceholder: 'ಹೆದ್ದಾರಿ (NH-27), ಜಿಲ್ಲೆಗಳು, ವಾಹನಗಳನ್ನು ಹುಡುಕಿ...',
    heroSubtitle: 'ಈಶಾನ್ಯದ 8 ರಾಜ್ಯಗಳಲ್ಲಿ ನಿರಂತರ ರಸ್ತೆ ಕಣ್ಗಾವಲು ಮತ್ತು ಸುರಕ್ಷಿತ ಸರಕು ಸಾಗಣೆ.',
    calculateSafeCorridor: 'ಸುರಕ್ಷಿತ ಮಾರ್ಗ ಲೆಕ್ಕಾಚಾರ',
    roadAccessibility: 'ರಸ್ತೆ ಪ್ರವೇಶಿಸುವಿಕೆ',
    ofArteries: 'ಮುಖ್ಯ ರಸ್ತೆಗಳ',
    activeHazards: 'ಸಕ್ರಿಯ ಅಪಾಯಗಳು',
    blockedRoads: 'ರಸ್ತೆ ಬಂದ್',
    fleetInTransit: 'ಸಾಗಣೆಯಲ್ಲಿರುವ ವಾಹನಗಳು',
    registeredCarriers: 'ನೋಂದಾಯಿತ ವಾಹನಗಳು',
    delayedMissions: 'ವಿಳಂಬವಾದ ಸಾಗಣೆ',
    needsReroute: 'ಪರ್ಯಾಯ ಮಾರ್ಗ ಅಗತ್ಯವಿದೆ',
    arterialHighwayStatus: 'ರಾಷ್ಟ್ರೀಯ ಹೆದ್ದಾರಿ ಸ್ಥಿತಿ',
    openGisMap: 'ಜಿಐಎಸ್ ನಕ್ಷೆ ತೆರೆಯಿರಿ',
    aiBriefingTitle: 'AI ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಬ್ರೀಫಿಂಗ್',
    optimizeRoutes: 'ಮಾರ್ಗ ಆಪ್ಟಿಮೈಸೇಶನ್',
    weatherRadar: 'ಹವಾಮಾನ ಮತ್ತು ಮಳೆ ರಾಡಾರ್',
    driverMission: 'ಚಾಲಕ ಸಕ್ರಿಯ ಮಿಷನ್',
    pickedUp: '1. ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    inTransit: '2. ಪ್ರಯಾಣದಲ್ಲಿದೆ',
    delayed: '3. ವಿಳಂಬ',
    delivered: '4. ತಲುಪಿಸಲಾಗಿದೆ',
    viewGpsRoute: 'ಜಿಪಿಎಸ್ ಸುರಕ್ಷಿತ ಬೈಪಾಸ್',
    reportBlockageSos: 'ರಸ್ತೆ ತಡೆ ವರದಿ (SOS)',
    verificationQueue: 'ಪರಿಶೀಲನೆ ಕ್ಯೂ',
    verifyBlock: 'ಪರಿಶೀಲಿಸಿ ರಸ್ತೆ ಬಂದ್ ಮಾಡಿ',
    reject: 'ತಿರಸ್ಕರಿಸಿ',
    languageSettings: 'ಭಾಷೆ ಮತ್ತು ಪ್ರಸಾರ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    broadcastLanguages: 'ಬಹುಭಾಷಾ ತುರ್ತು ಎಚ್ಚರಿಕೆ ಪ್ರಸಾರ',
    broadcastDesc: 'ತುರ್ತು ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು ಚಾಲಕರ ಸಂದೇಶಗಳಿಗಾಗಿ ಬಹು ಭಾಷೆಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    selectDisplayLang: 'ಪ್ರದರ್ಶನ ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    activeBroadcastCount: 'ಪ್ರಸಾರಕ್ಕಾಗಿ ಆಯ್ಕೆಮಾಡಿದ ಭಾಷೆಗಳು',
    applySelection: 'ಅನ್ವಯಿಸಿ',
    selectAll: 'ಎಲ್ಲವನ್ನೂ ಆಯ್ಕೆಮಾಡಿ (22)',
    clearAll: 'ಇಂಗ್ಲಿಷ್‌ಗೆ ಮರುಹೊಂದಿಸಿ',
    highways: 'ಹೆದ್ದಾರಿಗಳು',
    hazards: 'ಅಪಾಯಗಳು',
    vehicles: 'ವಾಹನಗಳು',
    riskZones: 'ಅಪಾಯ ವಲಯಗಳು',
    emergencyRoutes: 'ತುರ್ತು ಮಾರ್ಗಗಳು',
    corridorSafeBypass: 'ಸುರಕ್ಷಿತ ಬೈಪಾಸ್',
    allWeather: 'ಸುಲಭ ಸಂಚಾರ',
    caution: 'ಎಚ್ಚರಿಕೆ',
    blocked: 'ಬಂದ್'
  },
  ks: {
    appName: 'RouteMind NER',
    tagline: 'علاقائی لاجسٹکس تہٕ خطہٕ انٹیلی جنس',
    navDashboard: '1. ڈیش بورڈ',
    navMap: '2. لائیو نقشہٕ',
    navReports: '3. رپورٹس',
    reportHazard: 'خطرس متعلق اطلاع',
    live: 'لائیو',
    offline: 'آف لائن',
    syncPending: 'سنک',
    emergencyActive: 'ہنگامی حالت چالو',
    emergencyMode: 'ہنگامی پروٹوکول',
    searchPlaceholder: 'شاہراہ، ضلعہٕ یا گاڑی ژھانڈیو...',
    heroSubtitle: 'پہاڑی خطن مَنٛز محفوظ سڑک تہٕ رسد نظام۔',
    calculateSafeCorridor: 'محفوظ وتھ ژھانڈیو',
    roadAccessibility: 'سڑک دستیابی',
    ofArteries: 'شاہراہن ہنز',
    activeHazards: 'موجودہ خطرہٕ',
    blockedRoads: 'بند سڑک',
    fleetInTransit: 'سفر مَنٛز گاڑیہٕ',
    registeredCarriers: 'رجسٹرڈ گاڑیہٕ',
    delayedMissions: 'لیٹ مشن',
    needsReroute: 'بییہٕ وتھ ضرورت',
    arterialHighwayStatus: 'شاہراہک حال',
    openGisMap: 'نقشہٕ کھولوو',
    aiBriefingTitle: 'AI بریفنگ',
    optimizeRoutes: 'وتھ بناوو',
    weatherRadar: 'موسم تہٕ رود',
    driverMission: 'ڈرائیور مشن',
    pickedUp: '1. لوڈ',
    inTransit: '2. سفر مَنٛز',
    delayed: '3. لیٹ',
    delivered: '4. واتناوو',
    viewGpsRoute: 'GPS وتھ بچھو',
    reportBlockageSos: 'سڑک بند SOS',
    verificationQueue: 'تصدیق لائن',
    verifyBlock: 'تصدیق تہٕ بند کرو',
    reject: 'رد',
    languageSettings: 'زبان تہٕ نشریاتی سیٹنگز',
    broadcastLanguages: 'واریاہن زبانن مَنٛز الرٹ',
    broadcastDesc: 'ڈرائیورن تہٕ خبرن خٲطرٕ واریاہ زبانن ہنز انتخاب کریو۔',
    selectDisplayLang: 'ڈسپلے زبان ژارِو',
    activeBroadcastCount: 'نشریاتی زبانن ہنز تعداد',
    applySelection: 'لاگو کریو',
    selectAll: 'سٲری ژارِو (22)',
    clearAll: 'انگریزی',
    highways: 'شاہراہ',
    hazards: 'خطرات',
    vehicles: 'گاڑیہٕ',
    riskZones: 'خطرناک علاقے',
    emergencyRoutes: 'ہنگامی راستے',
    corridorSafeBypass: 'محفوظ بائی پاس',
    allWeather: 'کھلہٕ',
    caution: 'ہوشیار',
    blocked: 'بند'
  },
  kok: {
    appName: 'RouteMind NER',
    tagline: 'प्रादेशिक रसद आनी दोंगरी वाठार म्हायती',
    navDashboard: '1. डॅशबोर्ड',
    navMap: '2. थेट जीआयएस नकासो',
    navReports: '3. रसद अहवाल आनी नोंदी',
    reportHazard: 'धोक्याची वर्दी दिया',
    live: 'थेट',
    offline: 'ऑफलाइन',
    syncPending: 'सिंक करात',
    emergencyActive: 'आणीबाणी मोड चालू',
    emergencyMode: 'आणीबाणी प्रोटोकॉल',
    searchPlaceholder: 'महामार्ग, जिल्हो, गाडयो सोदात...',
    heroSubtitle: 'ईशान्य भारतांत सुरक्षीत दोंगरी रस्ते आनी रसद येरादारी.',
    calculateSafeCorridor: 'सुरक्षीत मार्ग काडात',
    roadAccessibility: 'रस्तो उपलब्धता',
    ofArteries: 'मुखेल रस्त्यांची',
    activeHazards: 'चालू धोके',
    blockedRoads: 'बंद रस्ते',
    fleetInTransit: 'प्रवासांतल्यो गाडयो',
    registeredCarriers: 'नोंदणीकृत वाहनां',
    delayedMissions: 'उशीर जाल्ली रसद',
    needsReroute: 'पर्यायी रस्तो जाय',
    arterialHighwayStatus: 'महामार्ग स्थिती',
    openGisMap: 'जीआयएस नकासो पळयात',
    aiBriefingTitle: 'AI रसद म्हायती',
    optimizeRoutes: 'मार्ग सुदारप',
    weatherRadar: 'दोंगरी हवामान आनी पावस',
    driverMission: 'चालक सक्रिय मिशन',
    pickedUp: '1. भरलें',
    inTransit: '2. प्रवासांत',
    delayed: '3. उसरां',
    delivered: '4. पावलें',
    viewGpsRoute: 'जीपीएस पर्यायी मार्ग',
    reportBlockageSos: 'रस्तो आडखळ SOS',
    verificationQueue: 'तपासणी वळ',
    verifyBlock: 'तपासून रस्तो बंद करात',
    reject: 'नकार',
    languageSettings: 'भास आनी प्रसारण मांडणी',
    broadcastLanguages: 'विविध भासांनी सुचोवणी',
    broadcastDesc: 'चालकां खातीर वेग-वेगळ्यो भासो वेंचून काडात.',
    selectDisplayLang: 'पडद्याची भास वेंचून काडात',
    activeBroadcastCount: 'प्रसारणा खातीर भासो',
    applySelection: 'लागू करात',
    selectAll: 'सगळ्यो वेंचून काडात (22)',
    clearAll: 'इंग्लिश',
    highways: 'महामार्ग',
    hazards: 'धोके',
    vehicles: 'गाडयो',
    riskZones: 'धोक्याचे वाठार',
    emergencyRoutes: 'आणीबाणी मार्ग',
    corridorSafeBypass: 'सुरक्षीत बायपास',
    allWeather: 'सुलभ',
    caution: 'सावध',
    blocked: 'बंद'
  },
  mai: {
    appName: 'RouteMind NER',
    tagline: 'क्षेत्रीय लॉजिस्टिक्स आ पहाड़ी इलाका सूचना तंत्र',
    navDashboard: '1. डैशबोर्ड',
    navMap: '2. लाइव जीआईएस मानचित्र',
    navReports: '3. लॉजिस्टिक्स रिपोर्ट',
    reportHazard: 'खतराक सूचना दिअ',
    live: 'लाइव',
    offline: 'ऑफलाइन',
    syncPending: 'सिंक करू',
    emergencyActive: 'आपातकालीन मोड सक्रिय',
    emergencyMode: 'संकटकालीन प्रोटोकॉल',
    searchPlaceholder: 'राजमार्ग, जिला, गाड़ी खोजू...',
    heroSubtitle: 'उत्तर-पूर्व के 8 राज्य में सुरक्षित सड़क आ आपूर्ति मार्ग निगरानी।',
    calculateSafeCorridor: 'सुरक्षित रस्ता खोजू',
    roadAccessibility: 'सड़क उपलब्धता',
    ofArteries: 'मुख्य मार्गक',
    activeHazards: 'सक्रिय खतरा',
    blockedRoads: 'अवरुद्ध सड़क',
    fleetInTransit: 'रस्ता में गाड़ी दल',
    registeredCarriers: 'पंजीकृत गाड़ी',
    delayedMissions: 'विलंबित खेप',
    needsReroute: 'वैकल्पिक रस्ता चाही',
    arterialHighwayStatus: 'राजमार्गक स्थिति',
    openGisMap: 'नक्शा देखू',
    aiBriefingTitle: 'एआई लॉजिस्टिक्स ब्रीफिंग',
    optimizeRoutes: 'मार्ग सुधारू',
    weatherRadar: 'पहाड़ी मौसम आ बरखा',
    driverMission: 'चालक मिशन',
    pickedUp: '1. उठायल गेल',
    inTransit: '2. रस्ता में अछि',
    delayed: '3. देरी भेल',
    delivered: '4. पहुँच गेल',
    viewGpsRoute: 'जीपीएस बाईपास देखू',
    reportBlockageSos: 'सड़क अवरोध SOS',
    verificationQueue: 'सत्यापन कतार',
    verifyBlock: 'सत्यापित कऽ रस्ता बंद करू',
    reject: 'अस्वीकार',
    languageSettings: 'भाषा आ प्रसारण सेटिंग्स',
    broadcastLanguages: 'बहुभाषी आपातकालीन प्रसारण',
    broadcastDesc: 'चालक आ सुरक्षाकर्मी लेल अनेक भाषा चुनु।',
    selectDisplayLang: 'प्रदर्शित भाषा चुनु',
    activeBroadcastCount: 'प्रसारण लेल चयनित भाषा',
    applySelection: 'लागू करू',
    selectAll: 'सब चुनु (22)',
    clearAll: 'अंग्रेज़ी',
    highways: 'राजमार्ग',
    hazards: 'खतरा',
    vehicles: 'गाड़ी',
    riskZones: 'जोखिम क्षेत्र',
    emergencyRoutes: 'आपातकालीन मार्ग',
    corridorSafeBypass: 'सुरक्षित बाईपास',
    allWeather: 'खुजल',
    caution: 'सावधान',
    blocked: 'बंद'
  },
  ml: {
    appName: 'RouteMind NER',
    tagline: 'മേഖലാ ലോജിസ്റ്റിക്സും പർവ്വത ഭൂപ്രകൃതി ഇന്റലിജൻസും',
    navDashboard: '1. ഡാഷ്‌ബോർഡ്',
    navMap: '2. തത്സമയ ജിഐഎസ് മാപ്പ്',
    navReports: '3. പ്രവർത്തന റിപ്പോർട്ടുകൾ',
    reportHazard: 'അപകടം റിപ്പോർട്ട് ചെയ്യുക',
    live: 'ലൈവ്',
    offline: 'ഓഫ്‌ലൈൻ',
    syncPending: 'സിങ്ക് ചെയ്യുക',
    emergencyActive: 'അടിയന്തരാവസ്ഥ സജീവം',
    emergencyMode: 'അടിയന്തര പ്രോട്ടോക്കോൾ',
    searchPlaceholder: 'ഹൈവേകൾ (NH-27), ജില്ലകൾ, വാഹനങ്ങൾ തിരയുക...',
    heroSubtitle: 'വടക്കുകിഴക്കൻ 8 സംസ്ഥാനങ്ങളിലെ സുരക്ഷിത പർവത പാത നിരീക്ഷണം.',
    calculateSafeCorridor: 'സുരക്ഷിത പാത കണ്ടെത്തുക',
    roadAccessibility: 'റോഡ് ലഭ്യത',
    ofArteries: 'പ്രധാന റോഡുകളുടെ',
    activeHazards: 'നിലവിലെ അപകടങ്ങൾ',
    blockedRoads: 'തടസ്സപ്പെട്ട റോഡ്',
    fleetInTransit: 'സഞ്ചാരത്തിലുള്ള വാഹനങ്ങൾ',
    registeredCarriers: 'രജിസ്റ്റർ ചെയ്ത വാഹനങ്ങൾ',
    delayedMissions: 'വൈകിയ ചരക്കുനീക്കം',
    needsReroute: 'മറ്റൊരു പാത ആവശ്യമാണ്',
    arterialHighwayStatus: 'ഹൈവേ സ്ഥിതിവിവരം',
    openGisMap: 'ജിഐഎസ് ഭൂപടം കാണുക',
    aiBriefingTitle: 'എഐ വിവരണം',
    optimizeRoutes: 'റൂട്ട് ഒപ്റ്റിമൈസ് ചെയ്യുക',
    weatherRadar: 'കാലാവസ്ഥയും മഴയും',
    driverMission: 'ഡ്രൈവർ ദൗത്യം',
    pickedUp: '1. എടുത്തു',
    inTransit: '2. വഴിയിലാണ്',
    delayed: '3. വൈകി',
    delivered: '4. എത്തിച്ചു',
    viewGpsRoute: 'ജിപിഎസ് ബൈപാസ് കാണുക',
    reportBlockageSos: 'റോഡ് തടസ്സം SOS',
    verificationQueue: 'പരിശോധന നിര',
    verifyBlock: 'സ്ഥിരീകരിച്ച് റോഡ് തടയുക',
    reject: 'നിരസിക്കുക',
    languageSettings: 'ഭാഷയും പ്രക്ഷേപണ ക്രമീകരണങ്ങളും',
    broadcastLanguages: 'ബഹുഭാഷാ അടിയന്തര മുന്നറിയിപ്പ്',
    broadcastDesc: 'അടിയന്തര സന്ദേശങ്ങൾ നൽകുന്നതിനായി ഒന്നിലധികം ഭാഷകൾ തിരഞ്ഞെടുക്കുക.',
    selectDisplayLang: 'പ്രദർശന ഭാഷ തിരഞ്ഞെടുക്കുക',
    activeBroadcastCount: 'പ്രക്ഷേപണത്തിനായി തിരഞ്ഞെടുത്ത ഭാഷകൾ',
    applySelection: 'പ്രയോഗിക്കുക',
    selectAll: 'എല്ലാം തിരഞ്ഞെടുക്കുക (22)',
    clearAll: 'ഇംഗ്ലീഷിലേക്ക് മാറ്റുക',
    highways: 'ഹൈവേകൾ',
    hazards: 'അപകടങ്ങൾ',
    vehicles: 'വാഹനങ്ങൾ',
    riskZones: 'അപകട മേഖലകൾ',
    emergencyRoutes: 'അടിയന്തര പാതകൾ',
    corridorSafeBypass: 'സുരക്ഷിത ബൈപാസ്',
    allWeather: 'സഞ്ചാരയോഗ്യം',
    caution: 'ജാഗ്രത',
    blocked: 'തടസ്സപ്പെട്ടു'
  },
  mr: {
    appName: 'RouteMind NER',
    tagline: 'प्रादेशिक लॉजिस्टिक्स व पर्वतीय भूभाग बुद्धिमत्ता मंच',
    navDashboard: '1. डॅशबोर्ड',
    navMap: '2. थेट जीआयएस नकाशा',
    navReports: '3. लॉजिस्टिक्स अहवाल व नोंदी',
    reportHazard: 'धोक्याची नोंद करा',
    live: 'थेट',
    offline: 'ऑफलाइन',
    syncPending: 'सिंक करा',
    emergencyActive: 'आणीबाणी मोड सक्रिय',
    emergencyMode: 'आणीबाणी प्रोटोकॉल',
    searchPlaceholder: 'महामार्ग (NH-27, NH-10), जिल्हे, वाहने शोधा...',
    heroSubtitle: 'ईशान्येकडील ८ राज्यांमध्ये अखंड पर्वतीय महामार्ग निरीक्षण व सुरक्षित पुरवठा.',
    calculateSafeCorridor: 'सुरक्षित पर्यायी मार्ग शोधा',
    roadAccessibility: 'रस्ता सुलभता',
    ofArteries: 'मुख्य रस्त्यांची',
    activeHazards: 'सक्रिय धोके / दरडी',
    blockedRoads: 'बंद रस्ते',
    fleetInTransit: 'प्रवासातील वाहने',
    registeredCarriers: 'नोंदणीकृत वाहने',
    delayedMissions: 'विलंबित पुरवठा',
    needsReroute: 'पर्यायी मार्ग आवश्यक',
    arterialHighwayStatus: 'प्रमुख महामार्ग स्थिती',
    openGisMap: 'जीआयएस नकाशा उघडा',
    aiBriefingTitle: 'एआय लॉजिस्टिक्स माहिती',
    optimizeRoutes: 'मार्ग अनुकूलन',
    weatherRadar: 'पर्वतीय हवामान व पर्जन्य',
    driverMission: 'चालक सक्रिय मोहीम डॅशबोर्ड',
    pickedUp: '1. स्वीकारले',
    inTransit: '2. प्रवासात',
    delayed: '3. उशीर',
    delivered: '4. वितरित केले',
    viewGpsRoute: 'जीपीएस पर्यायी बायपास पहा',
    reportBlockageSos: 'रस्ता अडथळा SOS',
    verificationQueue: 'धोका पडताळणी रांग',
    verifyBlock: 'पडताळणी करून रस्ता बंद करा',
    reject: 'नाकारा',
    languageSettings: 'भाषा व प्रसारण सेटिंग्ज',
    broadcastLanguages: 'बहुभाषिक आपत्कालीन प्रसारण',
    broadcastDesc: 'चालक आणि फील्ड कर्मचाऱ्यांसाठी एकाधिक प्रादेशिक भाषा निवडा.',
    selectDisplayLang: 'प्रदर्शित भाषा निवडा',
    activeBroadcastCount: 'प्रसारणासाठी निवडलेल्या भाषा',
    applySelection: 'जतन करा व लागू करा',
    selectAll: 'सर्व निवडा (22)',
    clearAll: 'इंग्रजीवर रीसेट करा',
    highways: 'महामार्ग',
    hazards: 'धोके',
    vehicles: 'वाहने',
    riskZones: 'धोकादायक क्षेत्र',
    emergencyRoutes: 'आणीबाणी मार्ग',
    corridorSafeBypass: 'सुरक्षित बायपास',
    allWeather: 'सुलभ',
    caution: 'सावधगिरी',
    blocked: 'बंद'
  },
  or: {
   appName: 'RouteMind NER',

  tagline: 'ଆଞ୍ଚଳିକ ପରିବହନ ଓ ପାର୍ବତ୍ୟ ଭୂଭାଗ ଗୁଇନ୍ଦା ମଞ୍ଚ',

  navDashboard: '୧. ଡ୍ୟାସବୋର୍ଡ',

  navMap: '୨. ଲାଇଭ୍ ଜିଆଇଏସ୍ ମ୍ୟାପ୍',

  navReports: '୩. ପରିଚାଳନ ରିପୋର୍ଟ',

  reportHazard:
    'ଉତ୍ତର-ପୂର୍ବାଞ୍ଚଳର ୮ ରାଜ୍ୟରେ ସୁରକ୍ଷିତ ରାସ୍ତା ନିରୀକ୍ଷଣ ଓ ଯୋଗାଣ ବ୍ୟବସ୍ଥା।',

  live: 'ଲାଇଭ୍',

  offline: 'ଅଫଲାଇନ୍',

  syncPending: 'ସିଙ୍କ୍ କରନ୍ତୁ',

  emergencyActive: 'ଜରୁରୀକାଳୀନ ସକ୍ରିୟ',

  emergencyMode: 'ଜରୁରୀକାଳୀନ ପ୍ରୋଟୋକଲ୍',

  searchPlaceholder: 'ରାଜପଥ (NH-27), ଜିଲ୍ଲା, ଗାଡ଼ି ଖୋଜନ୍ତୁ...',

  heroSubtitle:
    'ଉତ୍ତର-ପୂର୍ବାଞ୍ଚଳର ୮ ରାଜ୍ୟରେ ସୁରକ୍ଷିତ ରାସ୍ତା ନିରୀକ୍ଷଣ ଓ ଯୋଗାଣ ବ୍ୟବସ୍ଥା।',

  calculateSafeCorridor: 'ସୁରକ୍ଷିତ ରାସ୍ତା ବାହାର କରନ୍ତୁ',

  roadAccessibility: 'ରାସ୍ତା ସୁଗମତା',

  ofArteries: 'ମୁଖ୍ୟ ରାସ୍ତାର',

  activeHazards: 'ସକ୍ରିୟ ବିପଦ',

  blockedRoads: 'ଅବରୋଧ ରାସ୍ତା',

  fleetInTransit: 'ଯାତ୍ରାରେ ଥିବା ଗାଡ଼ି',

  registeredCarriers: 'ପଞ୍ଜୀକୃତ ଗାଡ଼ି',

  delayedMissions: 'ବିଳମ୍ବିତ ମିଶନ',

  needsReroute: 'ବିକଳ୍ପ ରାସ୍ତା ଆବଶ୍ୟକ',

  arterialHighwayStatus: 'ଜାତୀୟ ରାଜପଥ ସ୍ଥିତି',

  openGisMap: 'ଜିଆଇଏସ୍ ମ୍ୟାପ୍ ଖୋଲନ୍ତୁ',

  aiBriefingTitle: 'AI ପରିବହନ ବିବରଣୀ',

  optimizeRoutes: 'ବିକଳ୍ପ ମାର୍ଗ',

  weatherRadar: 'ପାଣିପାଗ ଓ ବର୍ଷା',

  driverMission: 'ଡ୍ରାଇଭର ସକ୍ରିୟ ମିଶନ',

  pickedUp: '୧. ଉଠାଗଲା',

  inTransit: '୨. ରାସ୍ତାରେ ଅଛି',

  delayed: '୩. ବିଳମ୍ବ',

  delivered: '୪. ପହଞ୍ଚିଗଲା',

  viewGpsRoute: 'GPS ବିକଳ୍ପ ମାର୍ଗ',

  reportBlockageSos: 'ରାସ୍ତା ବନ୍ଦ SOS',

  verificationQueue: 'ଯାଞ୍ଚ ଧାଡ଼ି',

  verifyBlock: 'ଯାଞ୍ଚ କରି ରାସ୍ତା ବନ୍ଦ କରନ୍ତୁ',

  reject: 'ପ୍ରତ୍ୟାଖ୍ୟାନ',

  languageSettings: 'ଭାଷା ଓ ପ୍ରସାରଣ ସେଟିଙ୍ଗସ୍',

  broadcastLanguages: 'ବହୁଭାଷୀ ବିପଦ ଚେତାବନୀ ପ୍ରସାରଣ',

  broadcastDesc:
    'ଜରୁରୀ ସୂଚନା ଓ ଡ୍ରାଇଭର ସତର୍କତା ପାଇଁ ଏକାଧିକ ଭାଷା ଚୟନ କରନ୍ତୁ।',

  selectDisplayLang: 'ପ୍ରଦର୍ଶନ ଭାଷା ଚୟନ କରନ୍ତୁ',

  activeBroadcastCount: 'ପ୍ରସାରଣ ପାଇଁ ଚୟନିତ ଭାଷା',

  applySelection: 'ପ୍ରୟୋଗ କରନ୍ତୁ',

  selectAll: 'ସବୁ ଚୟନ କରନ୍ତୁ (୨୨)',

  clearAll: 'ସବୁ ବାତିଲ କରନ୍ତୁ',

  highways: 'ରାଜପଥ',

  hazards: 'ବିପଦ',

  vehicles: 'ଗାଡ଼ି',

  riskZones: 'ବିପଦପୂର୍ଣ୍ଣ ଅଞ୍ଚଳ',

  emergencyRoutes: 'ଜରୁରୀ ମାର୍ଗ',

  corridorSafeBypass: 'ସୁରକ୍ଷିତ ବାଇପାସ୍',

  allWeather: 'ଖୋଲା',

  caution: 'ସତର୍କତା',

  blocked: 'ବନ୍ଦ',
  },
  pa: {
    appName: 'RouteMind NER',
    tagline: 'ਖੇਤਰੀ ਲੌਜਿਸਟਿਕਸ ਅਤੇ ਪਹਾੜੀ ਖੇਤਰ ਸੂਚਨਾ ਪ੍ਰਣਾਲੀ',
    navDashboard: '1. ਡੈਸ਼ਬੋਰਡ',
    navMap: '2. ਲਾਈਵ ਜੀ.ਆਈ.ਐਸ ਨਕਸ਼ਾ',
    navReports: '3. ਲੌਜਿਸਟਿਕਸ ਰਿਪੋਰਟਾਂ',
    reportHazard: 'ਖ਼ਤਰੇ ਦੀ ਰਿਪੋਰਟ ਕਰੋ',
    live: 'ਲਾਈਵ',
    offline: 'ਔਫਲਾਈਨ',
    syncPending: 'ਸਿੰਕ ਕਰੋ',
    emergencyActive: 'ਐਮਰਜੈਂਸੀ ਮੋਡ ਚਾਲੂ',
    emergencyMode: 'ਐਮਰਜੈਂਸੀ ਪ੍ਰੋਟੋਕੋਲ',
    searchPlaceholder: 'ਹਾਈਵੇ (NH-27), ਜ਼ਿਲ੍ਹੇ, ਵਾਹਨ ਲੱਭੋ...',
    heroSubtitle: 'ਉੱਤਰ-ਪੂਰਬੀ 8 ਰਾਜਾਂ ਵਿੱਚ ਨਿਰੰਤਰ ਸੜਕ ਨਿਗਰਾਨੀ ਅਤੇ ਸੁਰੱਖਿਅਤ ਸਪਲਾਈ।',
    calculateSafeCorridor: 'ਸੁਰੱਖਿਅਤ ਰਸਤਾ ਲੱਭੋ',
    roadAccessibility: 'ਸੜਕ ਪਹੁੰਚਯੋਗਤਾ',
    ofArteries: 'ਮੁੱਖ ਸੜਕਾਂ ਦੀ',
    activeHazards: 'ਮੌਜੂਦਾ ਖ਼ਤਰੇ',
    blockedRoads: 'ਬੰਦ ਸੜਕਾਂ',
    fleetInTransit: 'ਰਾਹ ਵਿੱਚ ਕਾਫ਼ਲੇ',
    registeredCarriers: 'ਰਜਿਸਟਰਡ ਵਾਹਨ',
    delayedMissions: 'ਦੇਰੀ ਵਾਲੇ ਮਿਸ਼ਨ',
    needsReroute: 'ਬਦਲਵਾਂ ਰਸਤਾ ਲੋੜੀਂਦਾ',
    arterialHighwayStatus: 'ਰਾਸ਼ਟਰੀ ਰਾਜਮਾਰਗ ਸਥਿਤੀ',
    openGisMap: 'ਜੀ.ਆਈ.ਐਸ ਨਕਸ਼ਾ ਖੋਲ੍ਹੋ',
    aiBriefingTitle: 'AI ਲੌਜਿਸਟਿਕਸ ਜਾਣਕਾਰੀ',
    optimizeRoutes: 'ਰਸਤਾ ਸੁਧਾਰ',
    weatherRadar: 'ਮੌਸਮ ਅਤੇ ਬਾਰਿਸ਼',
    driverMission: 'ਡਰਾਈਵਰ ਸਰਗਰਮ ਮਿਸ਼ਨ',
    pickedUp: '1. ਲੋਡ ਕੀਤਾ',
    inTransit: '2. ਰਸਤੇ ਵਿੱਚ',
    delayed: '3. ਦੇਰੀ',
    delivered: '4. ਪਹੁੰਚਾਇਆ ਗਿਆ',
    viewGpsRoute: 'ਜੀ.ਪੀ.ਐਸ ਬਾਈਪਾਸ ਦੇਖੋ',
    reportBlockageSos: 'ਸੜਕ ਬੰਦ SOS',
    verificationQueue: 'ਪੜਤਾਲ ਸੂਚੀ',
    verifyBlock: 'ਪੜਤਾਲ ਕਰਕੇ ਸੜਕ ਬੰਦ ਕਰੋ',
    reject: 'ਰੱਦ ਕਰੋ',
    languageSettings: 'ਭਾਸ਼ਾ ਅਤੇ ਪ੍ਰਸਾਰਣ ਸੈਟਿੰਗਾਂ',
    broadcastLanguages: 'ਬਹੁ-ਭਾਸ਼ਾਈ ਐਮਰਜੈਂਸੀ ਅਲਰਟ',
    broadcastDesc: 'ਡਰਾਈਵਰਾਂ ਅਤੇ ਐਮਰਜੈਂਸੀ ਅਲਰਟ ਭੇਜਣ ਲਈ ਕਈ ਭਾਸ਼ਾਵਾਂ ਚੁਣੋ।',
    selectDisplayLang: 'ਡਿਸਪਲੇ ਭਾਸ਼ਾ ਚੁਣੋ',
    activeBroadcastCount: 'ਚੁਣੀਆਂ ਗਈਆਂ ਭਾਸ਼ਾਵਾਂ',
    applySelection: 'ਲਾਗੂ ਕਰੋ',
    selectAll: 'ਸਾਰੀਆਂ ਚੁਣੋ (22)',
    clearAll: 'ਅੰਗਰੇਜ਼ੀ',
    highways: 'ਹਾਈਵੇ',
    hazards: 'ਖ਼ਤਰੇ',
    vehicles: 'ਵਾਹਨ',
    riskZones: 'ਖ਼ਤਰਨਾਕ ਖੇਤਰ',
    emergencyRoutes: 'ਐਮਰਜੈਂਸੀ ਰਸਤੇ',
    corridorSafeBypass: 'ਸੁਰੱਖਿਅਤ ਬਾਈਪਾਸ',
    allWeather: 'ਚਾਲੂ',
    caution: 'ਸਾਵਧਾਨ',
    blocked: 'ਬੰਦ'
  },
  sat: {
    appName: 'RouteMind NER',
    tagline: 'ᱴᱚᱴᱷᱟᱠᱤᱭᱟᱹ ᱞᱚᱡᱤᱥᱴᱤᱠᱥ ᱟᱨ ᱵᱩᱨᱩ ᱴᱷᱟᱶ ᱛᱚᱞᱟᱥ',
    navDashboard: '᱑. ᱰᱮᱥᱵᱳᱨᱰ',
    navMap: '᱒. ᱡᱤ.ᱟᱭ.ᱮᱥ ᱢᱮᱯ',
    navReports: '᱓. ᱨᱤᱯᱳᱨᱴ ᱟᱨ ᱞᱚᱜᱽ',
    reportHazard: 'ᱵᱤᱯᱚᱫᱽ ᱨᱤᱯᱳᱨᱴ ᱢᱮ',
    live: 'ᱞᱟᱭᱤᱵᱽ',
    offline: 'ᱚᱯᱷᱞᱟᱭᱤᱱ',
    syncPending: 'ᱥᱤᱝᱠ',
    emergencyActive: 'ᱦᱟᱦᱟᱠᱟᱨ ᱪᱟᱹᱞᱩ',
    emergencyMode: 'ᱮᱢᱟᱨᱡᱮᱱᱥᱤ ᱢᱳᱰ',
    searchPlaceholder: 'ᱰᱟᱦᱟᱨ, ᱡᱤᱞᱟᱹ, ᱜᱟᱹᱰᱤ ᱥᱮᱸᱫᱽᱨᱟᱭ ᱢᱮ...',
    heroSubtitle: 'ᱩᱛᱛᱚᱨ-ᱯᱩᱨᱩᱵᱽ ᱨᱮᱱᱟᱜ ᱘ ᱜᱚᱴᱟᱝ ᱯᱚᱱᱚᱛ ᱨᱮ ᱰᱟᱦᱟᱨ ᱧᱮᱞ-ᱥᱟᱢᱴᱟᱣ᱾',
    calculateSafeCorridor: 'ᱥᱩᱞᱩᱠ ᱰᱟᱦᱟᱨ ᱯᱟᱱᱛᱷᱟ',
    roadAccessibility: 'ᱰᱟᱦᱟᱨ ᱪᱟᱞᱟᱜ',
    ofArteries: 'ᱢᱩᱬ ᱰᱟᱦᱟᱨ',
    activeHazards: 'ᱱᱤᱛᱚᱜᱟᱜ ᱵᱤᱯᱚᱫᱽ',
    blockedRoads: 'ᱵᱚᱸᱫᱽ ᱰᱟᱦᱟᱨ',
    fleetInTransit: 'ᱦᱚᱨ ᱨᱮ ᱜᱟᱹᱰᱤ',
    registeredCarriers: 'ᱚᱞ ᱟᱠᱟᱱ ᱜᱟᱹᱰᱤ',
    delayedMissions: 'ᱵᱤᱞᱚᱢ ᱠᱟᱹᱢᱤ',
    needsReroute: 'ᱮᱴᱟᱜ ᱰᱟᱦᱟᱨ ᱞᱟᱹᱠᱛᱤ',
    arterialHighwayStatus: 'ᱢᱩᱬ ᱰᱟᱦᱟᱨ ᱦᱟᱞᱚᱛ',
    openGisMap: 'ᱢᱮᱯ ᱠᱷᱩᱞᱟᱹᱭ ᱢᱮ',
    aiBriefingTitle: 'AI ᱰᱟᱦᱟᱨ ᱠᱷᱚᱵᱚᱨ',
    optimizeRoutes: 'ᱰᱟᱦᱟᱨ ᱵᱮᱥ ᱢᱮ',
    weatherRadar: 'ᱫᱟᱜ-ᱡᱟᱹᱲᱤ ᱠᱷᱚᱵᱚᱨ',
    driverMission: 'ᱪᱟᱹᱞᱩᱣᱟᱹ ᱠᱟᱹᱢᱤ',
    pickedUp: '᱑. ᱤᱫᱤ ᱮᱱᱟ',
    inTransit: '᱒. ᱰᱟᱦᱟᱨ ᱨᱮ',
    delayed: '᱓. ᱵᱤᱞᱚᱢ',
    delivered: '᱔. ᱥᱮᱴᱮᱨ ᱮᱱᱟ',
    viewGpsRoute: 'GPS ᱮᱴᱟᱜ ᱰᱟᱦᱟᱨ',
    reportBlockageSos: 'ᱰᱟᱦᱟᱨ ᱵᱚᱸᱫᱽ SOS',
    verificationQueue: 'ᱯᱚᱨᱠᱷᱟᱣ ᱞᱟᱭᱤᱱ',
    verifyBlock: 'ᱯᱚᱨᱠᱷᱟᱣ ᱠᱟᱛᱮ ᱵᱚᱸᱫᱽ ᱢᱮ',
    reject: 'ᱵᱟᱹᱜᱤ',
    languageSettings: 'ᱯᱟᱹᱨᱥᱤ ᱟᱨ ᱯᱟᱥᱱᱟᱣ ᱥᱟᱡᱟᱣ',
    broadcastLanguages: 'ᱟᱭᱢᱟ ᱯᱟᱹᱨᱥᱤ ᱛᱮ ᱦᱩᱥᱤᱭᱟᱹᱨ',
    broadcastDesc: 'ᱪᱟᱹᱞᱩᱣᱟᱹ ᱟᱨ ᱦᱚᱲ ᱠᱚ ᱞᱟᱹᱜᱤᱫ ᱟᱭᱢᱟ ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱟᱣ ᱢᱮ᱾',
    selectDisplayLang: 'ᱧᱮᱞᱚᱜ ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱟᱣ',
    activeBroadcastCount: 'ᱵᱟᱪᱷᱟᱣ ᱟᱠᱟᱱ ᱯᱟᱹᱨᱥᱤ ᱠᱚ',
    applySelection: 'ᱞᱟᱜᱩᱭ ᱢᱮ',
    selectAll: 'ᱡᱚᱛᱚ ᱵᱟᱪᱷᱟᱣ (᱒᱒)',
    clearAll: 'ᱤᱝᱨᱟᱹᱡᱤ',
    highways: 'ᱢᱩᱬ ᱰᱟᱦᱟᱨ',
    hazards: 'ᱵᱤᱯᱚᱫᱽ',
    vehicles: 'ᱜᱟᱹᱰᱤ',
    riskZones: 'ᱵᱚᱛᱚᱨ ᱴᱷᱟᱶ',
    emergencyRoutes: 'ᱮᱢᱟᱨᱡᱮᱱᱥᱤ ᱰᱟᱦᱟᱨ',
    corridorSafeBypass: 'ᱥᱩᱞᱩᱠ ᱵᱟᱭᱯᱟᱥ',
    allWeather: 'ᱡᱷᱤᱡ',
    caution: 'ᱦᱩᱥᱤᱭᱟᱹᱨ',
    blocked: 'ᱵᱚᱸᱫᱽ'
  },
  sd: {
    appName: 'RouteMind NER',
    tagline: 'علائقائي لاجسٽڪس ۽ جابلو زميني معلومات',
    navDashboard: '1. ڊيش بورڊ',
    navMap: '2. لائيو جي آءِ ايس نقشو',
    navReports: '3. آپريشنل رپورٽون',
    reportHazard: 'خطرناڪ صورتحال جي رپورٽ',
    live: 'لائيو',
    offline: 'آف لائن',
    syncPending: 'سنڪ ڪريو',
    emergencyActive: 'ايمرجنسي فعال',
    emergencyMode: 'ايمرجنسي پروٽوڪول',
    searchPlaceholder: 'شاهراهون، ضلعا، گاڏيون ڳوليو...',
    heroSubtitle: 'جابلو علائقن ۾ محفوظ سپلائي ۽ رستا جي نگراني.',
    calculateSafeCorridor: 'محفوظ رستو ڳوليو',
    roadAccessibility: 'رستي جي رسائي',
    ofArteries: 'مکيه شاهراهن جي',
    activeHazards: 'فعال خطرا',
    blockedRoads: 'بند رستا',
    fleetInTransit: 'سفر ۾ گاڏيون',
    registeredCarriers: 'رجسٽرڊ گاڏيون',
    delayedMissions: 'دير ٿيل مشن',
    needsReroute: 'متبادل رستو گهربل',
    arterialHighwayStatus: 'شاهراهن جي حالت',
    openGisMap: 'جي آءِ ايس نقشو کوليو',
    aiBriefingTitle: 'AI لاجسٽڪ بريفنگ',
    optimizeRoutes: 'رستو بهتر ڪريو',
    weatherRadar: 'موسم ۽ برسات',
    driverMission: 'ڊرائيور مشن',
    pickedUp: '1. کنيو ويو',
    inTransit: '2. رستي ۾',
    delayed: '3. دير',
    delivered: '4. پهچايو ويو',
    viewGpsRoute: 'GPS متبادل رستو',
    reportBlockageSos: 'رستو بند SOS',
    verificationQueue: 'تصديق قطار',
    verifyBlock: 'تصديق ڪري رستو بند ڪريو',
    reject: 'رد ڪريو',
    languageSettings: 'ٻولي ۽ نشرياتي سيٽنگون',
    broadcastLanguages: 'ڪيترين ئي ٻولين ۾ خبرداري',
    broadcastDesc: 'ڊرائيورن ۽ ايمرجنسي الرٽ موڪلڻ لاءِ ٻوليون چونڊيو.',
    selectDisplayLang: 'ڊسپلي ٻولي چونڊيو',
    activeBroadcastCount: 'چونڊيل ٻوليون',
    applySelection: 'لاڳو ڪريو',
    selectAll: 'سڀ چونڊيو (22)',
    clearAll: 'انگريزي',
    highways: 'شاهراهون',
    hazards: 'خطرا',
    vehicles: 'گاڏيون',
    riskZones: 'خطرناڪ علائقا',
    emergencyRoutes: 'ايمرجنسي رستا',
    corridorSafeBypass: 'محفوظ بائي پاس',
    allWeather: 'کليل',
    caution: 'خبردار',
    blocked: 'بند'
  },
  ta: {
    appName: 'RouteMind NER',
    tagline: 'பிராந்திய தளவாடங்கள் மற்றும் மலைப்பகுதி உளவுத்துறை',
    navDashboard: '1. முகப்பு',
    navMap: '2. நேரலை ஜிஐஎஸ் வரைபடம்',
    navReports: '3. தளவாட அறிக்கைகள்',
    reportHazard: 'ஆபத்தை புகாரளிக்கவும்',
    live: 'நேரலை',
    offline: 'ஆஃப்லைன்',
    syncPending: 'ஒத்திசைக்கவும்',
    emergencyActive: 'அவசரகால நிலை இயங்குகிறது',
    emergencyMode: 'அவசர நெறிமுறை',
    searchPlaceholder: 'நெடுஞ்சாலை (NH-27), மாவட்டங்கள், வாகனங்களைத் தேடுங்கள்...',
    heroSubtitle: 'வடகிழக்கின் 8 மாநிலங்களில் தொடர்ச்சியான நெடுஞ்சாலை கண்காணிப்பு மற்றும் பாதுகாப்பான சரக்கு போக்குவரத்து.',
    calculateSafeCorridor: 'பாதுகாப்பான பாதையை கணக்கிடுங்கள்',
    roadAccessibility: 'சாலை அணுகல்',
    ofArteries: 'முக்கிய சாலைகளில்',
    activeHazards: 'செயலில் உள்ள ஆபத்துகள்',
    blockedRoads: 'தடைபட்ட சாலைகள்',
    fleetInTransit: 'பயணத்தில் உள்ள வாகனங்கள்',
    registeredCarriers: 'பதிவுசெய்யப்பட்ட வாகனங்கள்',
    delayedMissions: 'தாமதமான சரக்குகள்',
    needsReroute: 'மாற்றுப் பாதை தேவை',
    arterialHighwayStatus: 'நெடுஞ்சாலை நிலை',
    openGisMap: 'வரைபடத்தை திறக்கவும்',
    aiBriefingTitle: 'AI தளவாட வழிகாட்டல்',
    optimizeRoutes: 'மாற்றுப் பாதை',
    weatherRadar: 'வானிலை மற்றும் மழைப்பொழிவு',
    driverMission: 'ஓட்டுநர் செயலில் உள்ள பணி',
    pickedUp: '1. ஏற்றப்பட்டது',
    inTransit: '2. பயணத்தில் உள்ளது',
    delayed: '3. தாமதம்',
    delivered: '4. வழங்கப்பட்டது',
    viewGpsRoute: 'ஜிபிஎஸ் மாற்றுப் பாதை',
    reportBlockageSos: 'சாலை அடைப்பு SOS',
    verificationQueue: 'சரிபார்ப்பு வரிசை',
    verifyBlock: 'சரிபார்த்து சாலையை மூடவும்',
    reject: 'நிராகரி',
    languageSettings: 'மொழி மற்றும் ஒளிபரப்பு அமைப்புகள்',
    broadcastLanguages: 'பன்மொழி அவசர எச்சரிக்கை ஒளிபரப்பு',
    broadcastDesc: 'ஓட்டுநர்கள் மற்றும் அவசர எச்சரிக்கைகளை அனுப்ப பல மொழிகளைத் தேர்ந்தெடுக்கவும்.',
    selectDisplayLang: 'காட்சி மொழியைத் தேர்ந்தெடுக்கவும்',
    activeBroadcastCount: 'தேர்ந்தெடுக்கப்பட்ட மொழிகள்',
    applySelection: 'பயன்படுத்து',
    selectAll: 'அனைத்தையும் தேர்ந்தெடு (22)',
    clearAll: 'ஆங்கிலம்',
    highways: 'நெடுஞ்சாலைகள்',
    hazards: 'ஆபத்துகள்',
    vehicles: 'வாகனங்கள்',
    riskZones: 'ஆபத்து மண்டலங்கள்',
    emergencyRoutes: 'அவசர வழிகள்',
    corridorSafeBypass: 'பாதுகாப்பான பைபாஸ்',
    allWeather: 'செல்லக்கூடியது',
    caution: 'எச்சரிக்கை',
    blocked: 'தடைபட்டது'
  },
  te: {
    appName: 'RouteMind NER',
    tagline: 'ప్రాంతీయ లాజిస్టిక్స్ మరియు పర్వత భూభాగ సమాచార వేదిక',
    navDashboard: '1. డ్యాష్‌బోర్డ్',
    navMap: '2. ప్రత్యక్ష జిఐఎస్ మ్యాప్',
    navReports: '3. కார்யாதரண நிவேதிகள்',
    reportHazard: 'பிழையை அறிவிக்கவும்',
    live: 'లైవ్',
    offline: 'ఆఫ్‌లైన్',
    syncPending: 'సింక్ చేయండి',
    emergencyActive: 'అత్యవసర మోడ్ యాక్టివ్',
    emergencyMode: 'అత్యవసర ప్రోటోకాల్',
    searchPlaceholder: 'హైవేలు (NH-27), జిల్లాలు, వాహనాలను శోధించండి...',
    heroSubtitle: 'ఈశాన్య 8 రాష్ట్రాలలో నిరంతర రహదారి నిఘా మరియు సురక్షిత సరఫరా మార్గాలు.',
    calculateSafeCorridor: 'సురక్షిత ప్రత్యామ్నాయ మార్గం కనుగొనండి',
    roadAccessibility: 'రహదారి ప్రాప్యత',
    ofArteries: 'ప్రధాన మార్గాలలో',
    activeHazards: 'ప్రస్తుత ప్రమాదాలు',
    blockedRoads: 'మూసివేసిన రోడ్లు',
    fleetInTransit: 'ప్రయాణంలో ఉన్న వాహనాలు',
    registeredCarriers: 'నమోదైన వాహనాలు',
    delayedMissions: 'ఆలస్యమైన రవాణా',
    needsReroute: 'ప్రత్యామ్నాయ మార్గం అవసరం',
    arterialHighwayStatus: 'జాతీయ రహదారుల స్థితి',
    openGisMap: 'జిఐఎస్ మ్యాప్ చూడండి',
    aiBriefingTitle: 'AI లాజిస్టిక్స్ సమాచారం',
    optimizeRoutes: 'మార్గ ఆప్టిమైజేషన్',
    weatherRadar: 'వాతావరణం మరియు వర్షపాతం',
    driverMission: 'డ్రైవర్ మిషన్ HUD',
    pickedUp: '1. లోడ్ చేయబడింది',
    inTransit: '2. మార్గంలో ఉంది',
    delayed: '3. ఆలస్యం',
    delivered: '4. డెలివరీ పూర్తయింది',
    viewGpsRoute: 'జీపీఎస్ సురక్షిత బైపాస్',
    reportBlockageSos: 'రహదారి అడ్డంకి SOS',
    verificationQueue: 'ధృవీకరణ క్యూ',
    verifyBlock: 'ధృవీకరించి రోడ్డును మూసివేయండి',
    reject: 'తిరస్కరించండి',
    languageSettings: 'భాష మరియు ప్రసార సెట్టింగ్‌లు',
    broadcastLanguages: 'బహుభాషా అత్యవసర హెచ్చరిక ప్రసారం',
    broadcastDesc: 'డ్రైవర్లు మరియు హెచ్చరికల కోసం బహుళ ప్రాంతీయ భాషలను ఎంచుకోండి.',
    selectDisplayLang: 'ప్రదర్శన భాషను ఎంచుకోండి',
    activeBroadcastCount: 'ఎంపిక చేసిన భాషలు',
    applySelection: 'వర్తింపజేయి',
    selectAll: 'అన్నీ ఎంచుకోండి (22)',
    clearAll: 'ఇంగ్లీష్',
    highways: 'హైవేలు',
    hazards: 'ప్రమాదాలు',
    vehicles: 'వాహనాలు',
    riskZones: 'ప్రమాద మండలాలు',
    emergencyRoutes: 'అత్యవసర మార్గాలు',
    corridorSafeBypass: 'సురక్షిత బైపాస్',
    allWeather: 'అందుబాటులో ఉంది',
    caution: 'హెచ్చరిక',
    blocked: 'మూసివేయబడింది'
  },
  ur: {
    appName: 'RouteMind NER',
    tagline: 'علاقائی لاجسٹکس اور پہاڑی خطہ انٹیلی جنس',
    navDashboard: '1. ڈیش بورڈ',
    navMap: '2. لائیو جی آئی ایس نقشہ',
    navReports: '3. آپریشنل رپورٹس و لاگز',
    reportHazard: 'خطرے کی اطلاع دیں',
    live: 'لائیو',
    offline: 'آف لائن',
    syncPending: 'سنک کریں',
    emergencyActive: 'ایمرجنسی فعال ہے',
    emergencyMode: 'ایمرجنسی پروٹوکول',
    searchPlaceholder: 'ہائی ویز (NH-27, NH-10)، اضلاع، گاڑیاں تلاش کریں...',
    heroSubtitle: 'شمال مشرقی 8 ریاستوں میں محفوظ پہاڑی راستوں اور ضروری سامان کی ترسیل کی نگرانی۔',
    calculateSafeCorridor: 'محفوظ متبادل راستہ تلاش کریں',
    roadAccessibility: 'سڑک کی رسائی',
    ofArteries: 'اہم شاہراہوں کی',
    activeHazards: 'موجودہ خطرات',
    blockedRoads: 'بند سڑکیں',
    fleetInTransit: 'سفر میں قافلے',
    registeredCarriers: 'رجسٹرڈ گاڑیاں',
    delayedMissions: 'تاخیر کا شکار ترسیل',
    needsReroute: 'متبادل راستہ درکار ہے',
    arterialHighwayStatus: 'قومی شاہراہوں کی صورتحال',
    openGisMap: 'جی آئی ایس نقشہ کھولیں',
    aiBriefingTitle: 'AI لاجسٹکس بریفنگ',
    optimizeRoutes: 'راستے کی بہتری',
    weatherRadar: 'پہاڑی موسم اور بارش',
    driverMission: 'ڈرائیور مشن کنٹرول',
    pickedUp: '1. لوڈ کیا گیا',
    inTransit: '2. راستے میں ہے',
    delayed: '3. تاخیر',
    delivered: '4. پہنچا دیا گیا',
    viewGpsRoute: 'GPS محفوظ بائی پاس دیکھیں',
    reportBlockageSos: 'سڑک بندش SOS',
    verificationQueue: 'تصدیقی قطار',
    verifyBlock: 'تصدیق کر کے راستہ بند کریں',
    reject: 'مسترد کریں',
    languageSettings: 'زبان اور نشریاتی ترتیبات',
    broadcastLanguages: 'کثیر لسانی ہنگامی انتباہ نشریات',
    broadcastDesc: 'ڈرائیوروں اور امدادی دستوں کو پیغامات بھیجنے کے لیے متعدد علاقائی زبانیں منتخب کریں۔',
    selectDisplayLang: 'ڈسپلے زبان منتخب کریں',
    activeBroadcastCount: 'نشریات کے لیے منتخب زبانیں',
    applySelection: 'لاگو کریں',
    selectAll: 'سب منتخب کریں (22)',
    clearAll: 'انگریزی',
    highways: 'شاہراہیں',
    hazards: 'خطرات',
    vehicles: 'گاڑیاں',
    riskZones: 'خطرناک زونز',
    emergencyRoutes: 'ہنگامی راستے',
    corridorSafeBypass: 'محفوظ بائی پاس',
    allWeather: 'کھلی سڑک',
    caution: 'احتیاط',
    blocked: 'بند'
  }
};

interface LanguageContextType {
  currentLanguage: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  broadcastLanguages: LanguageCode[];
  toggleBroadcastLanguage: (lang: LanguageCode) => void;
  selectAllBroadcastLanguages: () => void;
  clearBroadcastLanguages: () => void;
  t: (key: TranslationKey) => string;
  languages: LanguageInfo[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const STORAGE_KEY_LANG = 'pandavas_ui_lang';
const STORAGE_KEY_BROADCAST = 'pandavas_broadcast_langs';

// Default multi-language broadcast set for Northeast India corridors
const DEFAULT_BROADCAST_LANGS: LanguageCode[] = ['en', 'as', 'bn', 'hi', 'mni', 'ne', 'brx'];

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguageState] = useState<LanguageCode>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY_LANG) as LanguageCode;
      if (saved && TRANSLATIONS[saved]) return saved;
    } catch (_) {}
    return 'en';
  });

  const [broadcastLanguages, setBroadcastLanguages] = useState<LanguageCode[]>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY_BROADCAST);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (Array.isArray(parsed) && parsed.length > 0) return parsed;
      }
    } catch (_) {}
    return DEFAULT_BROADCAST_LANGS;
  });

  const setLanguage = (lang: LanguageCode) => {
    setCurrentLanguageState(lang);
    try {
      localStorage.setItem(STORAGE_KEY_LANG, lang);
    } catch (_) {}
  };

  const toggleBroadcastLanguage = (lang: LanguageCode) => {
    setBroadcastLanguages(prev => {
      let updated: LanguageCode[];
      if (prev.includes(lang)) {
        if (prev.length <= 1) return prev; // Keep at least one
        updated = prev.filter(l => l !== lang);
      } else {
        updated = [...prev, lang];
      }
      try {
        localStorage.setItem(STORAGE_KEY_BROADCAST, JSON.stringify(updated));
      } catch (_) {}
      return updated;
    });
  };

  const selectAllBroadcastLanguages = () => {
    const all = SUPPORTED_LANGUAGES.map(l => l.code);
    setBroadcastLanguages(all);
    try {
      localStorage.setItem(STORAGE_KEY_BROADCAST, JSON.stringify(all));
    } catch (_) {}
  };

  const clearBroadcastLanguages = () => {
    setBroadcastLanguages(['en']);
    try {
      localStorage.setItem(STORAGE_KEY_BROADCAST, JSON.stringify(['en']));
    } catch (_) {}
  };

  const t = (key: TranslationKey): string => {
    const langDict = TRANSLATIONS[currentLanguage];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    return TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        setLanguage,
        broadcastLanguages,
        toggleBroadcastLanguage,
        selectAllBroadcastLanguages,
        clearBroadcastLanguages,
        t,
        languages: SUPPORTED_LANGUAGES
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
